name: Build and validate token list JSON
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat ./.nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node + pnpm
      uses: actions/setup-node@v4
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "pnpm"
    - run: pnpm install --frozen-lockfile
    - name: Run linting
      run: pnpm lint
    - name: Run tests
      run: pnpm test
    - name: Build token list for PRs
      if: github.ref != 'refs/heads/main'
      run: pnpm build
    - name: Build token list for main
      if: github.ref == 'refs/heads/main'
      run: pnpm build
      env:
        FLEEK_STORAGE_API_KEY: ${{ secrets.FLEEK_STORAGE_API_KEY }}
        FLEEK_STORAGE_API_SECRET: ${{ secrets.FLEEK_STORAGE_API_SECRET }}
    - name: Upload token list as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: tallycash.tokenlist.json
        path: build/tallycash.tokenlist.json
